version: '3.1'

services:
  node:
    build:
      dockerfile: Dockerfile
      context: .
    
    command: yarn build

    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production